/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_imageEffectApplication_libraryInterfaces_DominantColourInterface */

#ifndef _Included_com_iiitb_imageEffectApplication_libraryInterfaces_DominantColourInterface
#define _Included_com_iiitb_imageEffectApplication_libraryInterfaces_DominantColourInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_imageEffectApplication_libraryInterfaces_DominantColourInterface
 * Method:    applyDominantColour
 * Signature: ([[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;)[[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_imageEffectApplication_libraryInterfaces_DominantColourInterface_applyDominantColour
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
